/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConversionHistory: typeof import('./components/ConversionHistory.vue')['default']
    DialogAuthenticate: typeof import('./components/DialogAuthenticate.vue')['default']
    Documentselector: typeof import('./components/Documentselector.vue')['default']
    DocumentSelector: typeof import('./components/DocumentSelector.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview.vue')['default']
    ImageUploader: typeof import('./components/ImageUploader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
